### ISSUE TITLE
Steps to integrate all branches into working apps

### ISSUE THREAD

**Issue by Coder02Aniket** [Awad-Safwat/qwiker#11]
Hi awad ,  I found your app very interesting and also want to try running the app can you please tell me steps to run app. I am getting many errors , please tell me steps to run both driver and user side app running. Thanks a lot  !!!

**Comment by lololo1906** [comment]
heyyy I am facing the same issue as well on my Android Studio, Can you help me on the steps to run the app for the driver as welll as the rider
